
export const SAVE_USERINFO = 'SAVE_USERINFO'
export const SAVE_ARTICLEINFO = 'SAVE_ARTICLEINFO'
export const SAVE_TEAMONE = 'SAVE_TEAMONE'
export const SAVE_BOOKINFO = 'SAVE_BOOKINFO'
export const SAVE_FRIENDLINK = 'SAVE_FRIENDLINK'
